# Goal
string sentence

string language # Only for Philips, Google
string character # Only for Philips
string emotion # Only for Philips
string voice # Only for Philips

bool slow # Only for Google
---
# Result
---
# Feedback
duration remaining_time
