#! /usr/bin/python

from text_to_speech_msgs.srv import Play, PlayRequest

from os import path
import sys
import rospy


def main():
    rospy.init_node('play_audio')

    if len(sys.argv) != 3:
        print("Usage: play FILENAME SERVICE_NAME")
        return 1

    filename = sys.argv[1]
    service_name = sys.argv[2]

    rospy.wait_for_service(service_name)

    try:
        srv_play = rospy.ServiceProxy(service_name, Play)

        req = PlayRequest()
        ext = path.splitext(filename)[-1]
        req.audio_type = ext.lstrip(".")
        with open(filename, "rb") as f:
            req.audio_data = f.read()
        req.blocking_call = False

        resp = srv_play(req)
        print(resp)
    except rospy.ServiceException as e:
        print("Service call failed: {}".format(e))


if __name__ == "__main__":
    sys.exit(main())
